[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "foundry-devops/=lib/foundry-devops/",
]
ffi = true
# allow foundry to run commands directly on machine

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
